admin node search exlusions:
  title: 'Exlude nodes from search results'
  description: 'This allows users with this permission to flag content as not to be searched.'
  restrict access: TRUE

search all content:
  title: 'Search all content types'
  description: 'Allow users to search any content, overriding content type permissions.'
  restrict access: TRUE

search all exluded entities:
  title: 'Search exluded content'
  description: 'Allow users to search any content, overriding individual content item exlusion settings.'
  restrict access: TRUE

permission_callbacks:
  - search_configPermissions: