search_config.node_content_settings:
    type: config_object
        mapping:
            move_keyword_search:
                type: checkbox
                label: Move basic keyword search
            advanced_populate:
                type: checkbox
                label: Populate the advanced form with default values
            remove_containing_wrapper:
                type: radios
                label: Removing all Containing ... keywords
            advanced_expand:
                type: radios
                label: Control how the advanced form initially renders